version: '3'

services:
    ctf:
        restart: always
        build: ./
        networks:
            - internal
    proxy:
        restart: always
        image: nginx
        ports:
            - '30008:30008'
        volumes:
            - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - default
            - internal
        depends_on:
            - ctf

networks:
    default:
    internal:
        internal: true